### ISSUE TITLE
Country activity repeating letter.

### ISSUE THREAD

**Issue by JarodO** [sugarlabs/sugar#755]
In the country activity, where you name one country for each letter except for w and x, the input will occasionally repeat, as if a key is stuck. Leaving the activity and then returning stops the repeating input, ruling out a keyboard issue, and I made a second copy of Sugar on a Stick that also has the same issue, ruling out the flash drive itself being a cause. It still could be my computer, but my computer has not had issues like this elsewhere.

**Comment by quozl** [comment]
Thanks.  Reproduced in Countries-33 on Debian.  Key events are either missed or repeat.  Log activity shows no helpful errors.  Problem doesn't affect other activities, so it isn't a problem with Sugar itself.  Moving this issue to the Countries activity.
