### ISSUE TITLE
Unable to get Paint to start.

### ISSUE THREAD

**Issue by TreeBaron** [sugarlabs/sugar#757]
I was not able to get the Paint app to start. It displays this message, "Paint failed to start." Screenshot attached.

![20170529_144434](https://cloud.githubusercontent.com/assets/8785617/26759201/9442c1e8-48ac-11e7-8ff9-785e98af386b.jpg)

**Comment by i5o** [comment]
Hi @TreeBaron thanks for reporting this.

What version of Sugar/Paint activity are you using?
If you could attach the logs that would help us a lot.

Logs are available in:
/home/*username*/.sugar/default/logs/

If you are using sugar-build:
sugar-build/dotsugar/default/logs

Thanks,
Ignacio!

**Comment by quozl** [comment]
There was a bug just fixed.

Please upgrade to Paint-66 and try again.

http://activities.sugarlabs.org/en-US/sugar/addon/4082/
