### ISSUE TITLE
Unable to get Physics to start.

### ISSUE THREAD

**Issue by TreeBaron** [sugarlabs/sugar#758]
I was unable to get Physics to start, this message was displayed: "Physics failed to start.
![20170529_144551](https://cloud.githubusercontent.com/assets/8785617/26759210/c7c2a40c-48ac-11e7-8a7b-792428066fb1.jpg)
"

**Comment by i5o** [comment]
Hi @TreeBaron thanks for reporting this.
Same comment as prev :)

What version of Sugar/Physics activity are you using?
If you could attach the logs that would help us a lot.

Logs are available in:
/home/*username*/.sugar/default/logs/

If you are using sugar-build:
sugar-build/dotsugar/default/logs

Thanks,
Ignacio!

**Comment by walterbender** [comment]
Are you using a 32bit, 64bit, or ARM computer? (We've been chasing a bug with the 32bit version.)

**Comment by TreeBaron** [comment]
Hello, I am running sugar labs on a Lenovo x201 laptop. 

It has 4.00 GB ram, core i5 CPU M 520 @2.50GHz

It has a 64-bit version of windows on it, but it only has 4 gb of ram so I'm not sure how that's supposed to work. As for sugar I'm running Fedora-SoaS-Live 2.

**Comment by quozl** [comment]
Where did you get Fedora SoaS Live 2?

**Comment by TreeBaron** [comment]
Whoops, that was a typo. I'm on Fedora-Soas-Live 25

**Comment by TreeBaron** [comment]
I believe I downloaded the 64-bit version of sugar.

**Comment by quozl** [comment]
Okay, I can guess exactly which problem you hit, and you can upgrade to Physics-32 to fix it.

* http://people.sugarlabs.org/~quozl/Physics-32.xo

When you check for bugs already reported, be sure to check our trac instance at bugs.sugarlabs.org, to avoid wasting your time;

* https://bugs.sugarlabs.org/ticket/4986
* https://bugs.sugarlabs.org/ticket/4980
* https://bugs.sugarlabs.org/ticket/4976
