### ISSUE TITLE
Emoji's Do Not Fit On Icon Bar

### ISSUE THREAD

**Issue by TreeBaron** [sugarlabs/sugar#759]
Under Chat Activity - Emoji icon bar extends down rather far. Emojis go off of my screen to the right. See Screenshot.
![20170529_141451](https://cloud.githubusercontent.com/assets/8785617/26759219/02016644-48ad-11e7-8ebf-b42d2b16a2a0.jpg)

**Comment by walterbender** [comment]
Seems like a bug. Curious: How/where are you running Sugar? What size screen?

**Comment by TreeBaron** [comment]
I'm running sugar on a stick ( I'm running Fedora-SoaS-Live 2) on my Lenovo x201 laptop at a resolution of 1280x800.

**Comment by quozl** [comment]
Looks like the code preferences the XO display form factor.

Using Alt+1 screenshot, captured from Fedora 18 on XO-4 at 1200x900 pixels

![chat-fedora-18](https://cloud.githubusercontent.com/assets/2936481/26814346/3a2cd8e2-4ac8-11e7-88f6-56d11066aa2a.png)

and from Ubuntu on KVM at 1024x768 pixels

![chat-ubuntu-16 04](https://cloud.githubusercontent.com/assets/2936481/26814354/52cc7ee8-4ac8-11e7-8f7c-81ffdc055b45.png)

and from Ubuntu 16.04 on NL3 at 133x768 pixels

![chat-ubuntu-16 04-nl3](https://cloud.githubusercontent.com/assets/2936481/26814754/428c2c24-4acb-11e7-9ff9-98a3126ec6aa.png)

we see that;

* the calculated column count of the Gtk.Grid is wrong, [`smilies_columns` in `_create_smiley_table`](https://github.com/sugarlabs/chat/blob/master/activity.py#L235),
* the calculated width of the Gtk.ScrolledWindow is wrong, [`width` in `_create_smiley_window`](https://github.com/sugarlabs/chat/blob/master/activity.py#L594),
* the icons are not centred in their grid cells.

Workaround is to use the provided horizontal scroll bar that is shown in the screenshots but not @TreeBaron's photograph.
