### ISSUE TITLE
Text To Speech - Expletives

### ISSUE THREAD

**Issue by TreeBaron** [sugarlabs/sugar#764]
Text To Speech - Was able to make text to speech application say expletives. Using the following: “phuck”,”ass". **Any expletive word censorship can be overridden by adding the “^” character before it. This character makes no sound so it just sounds like the normal expletive. Possibly other characters behave in the same way. I suggest creating or finding an extensive list of words to ban, or providing users the option to create a black list of words**

**Comment by quozl** [comment]
Yes, the censorship chosen by the Speak activity authors is very mild and easily bypassed.  You can find the word list in the source repository 

* https://github.com/sugarlabs/speak/blob/152e474a5a24458b1a049721c0b3b43f7dc79607/face.py#L245

along with the method used to find the words relying on whitespace.

Thanks for publishing a method to bypass.  Your method relies on defeating the whitespace word split.

Another method to bypass is to remove the references to `remove_curses`, using the Develop activity.

It is not practical to maintain the list of words in each language and locale.

I've removed the curse filter from the Speak activity;

* https://github.com/sugarlabs/speak/commit/a28ca6bd7939f2fa66994dfff57bb4d7f0b738ef

Please enforce any local policy with appropriate social controls once Speak is upgraded to v54.
