### ISSUE TITLE
Story Activity - Text To Speech Censorship For Expletives

### ISSUE THREAD

**Issue by TreeBaron** [sugarlabs/sugar#765]
Story Activity - Story activity appears to have no censorship on text to speech whatsoever. I recommend implementing some version of this. I know if I was a child who had text to speech like this I'd have countless hours of fun figuring out how to get the computer to cuss. I know that as software developers it's not necessarily your job to monitor that closely, but at least making it a bit more difficult for kids to do would be nice.

**Comment by quozl** [comment]
No thanks.  Maintaining a list of expletives across all supported languages is impractical.  Expletives are context dependent.  Inappropriate use of expletives are a social problem and should be controlled as such.
