### ISSUE TITLE
Strange Word In Abacus App?

### ISSUE THREAD

**Issue by TreeBaron** [sugarlabs/sugar#766]
Abacus - In English mode in the abacus it has what appears to be a foreign word Caacupe’ next to the reset button. See screenshot.

![20170529_151429](https://cloud.githubusercontent.com/assets/8785617/26759276/6941a282-48ae-11e7-9a91-d501a5150ad3.jpg)

**Comment by i5o** [comment]
@walterbender may help here.

But I think it's the type/mode of abacus.

**Comment by walterbender** [comment]
Caacupe is the name of one of the abacus modes. It comes from the name of the town where the teachers who invented this mode live.
