### ISSUE TITLE
Journal placed above Home after startup

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar#769]
In previous versions, Sugar startup shows the home view, a busy cursor, asynchronously starts the journal, and then turns off the busy cursor leaving the home view available.

In Ubuntu 17.10 Artful, Sugar startup shows the home view, a busy cursor, but the journal window is created above the home window.

Related to https://github.com/sugarlabs/sugar-toolkit-gtk3/issues/368

**Comment by satellitee** [comment]
also found in fedora soas f27 and f28 rawhide
https://bugzilla.redhat.com/show_bug.cgi?id=1519042

**Comment by quozl** [comment]
Caused by upgrade of metacity from 3.24.0 to 3.25.2, git bisect shows first bad commit is [unminimize windows with initial IconicState if first known on MapRequest](https://github.com/GNOME/metacity/commit/6875256e63fbfd4500ddd27a7bf1aafc8d4c1ca3 ported from [mutter](https://gitlab.gnome.org/GNOME/mutter/commit/be5c2eb).

**Comment by nullr0ute** [comment]
We should probably report it upstream with metacity to get details.

**Comment by quozl** [comment]
Thanks, that would be great.  I could not figure out where to report it upstream.

**Comment by aperezbios** [comment]
@quozl , https://gitlab.gnome.org/GNOME/metacity/issues

**Comment by quozl** [comment]
@aperezbios, thanks.  Banner blindness.  https://gitlab.gnome.org/GNOME/metacity/issues/4

**Comment by quozl** [comment]
Fixed in https://github.com/GNOME/metacity/commit/074af8f87ef89b13ff326fb5d04ee424bbfd4ced
