### ISSUE TITLE
Make gender selection optional

### ISSUE THREAD

**Issue by icarito** [sugarlabs/sugar#770]
Off by default. Let deployments who want it activate it.

**Comment by jamessandy** [comment]
Yeah I think that  gender selection should be based on decision because some people may see it from a different view of racism

**Comment by quozl** [comment]
Was asked for more detail about this issue; here's a checklist.

- [ ] review the feature implementation, both in [requirements](https://wiki.sugarlabs.org/go/Features/About_Me) and code,
- [ ] find if the feature is already optional, and if so change the default,
- [ ] if the feature is not yet optional, add GSettings schema, conditional code, and set the default off.

**Comment by quozl** [comment]
https://github.com/sugarlabs/sugar/commit/70011a37b4d0c6ec0c5585355c76afd14a41a5b8
