### ISSUE TITLE
Journal entry name edit followed by tab is undone

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar#771]
Reproducer: expose the journal (F5), click on a journal entry name, change the name, press TAB.

Expected result: name change is accepted.

Observed result: name change is abandoned.

**Comment by Pro-Panda** [comment]
@quozl I would like to work on this issue.

**Comment by quozl** [comment]
Good, thanks.  Let us know if you stop.

**Comment by quozl** [comment]
Thanks, a good investigation.

In summary, using `esc` or `tab` emits `editing-canceled` by design in GTK+ 3 class `Gtk.CellRendererText`.  User should instead use `enter` for a change to be accepted.

This problem report probably arose from different behaviour in the three places where Sugar exposes the journal entry name;

* the activity toolbar title entry; which ignores `enter`, accepts on `tab`, but has no cancel, (added as https://github.com/sugarlabs/sugar-toolkit-gtk3/issues/375)
* the journal list view; which accepts on `enter` or click outside, and cancels on `tab` or `esc`, and;
* the journal object detail view; which accepts on `enter`, `tab`, or `esc`, with secondary effect that `esc` will dismiss the view.
