### ISSUE TITLE
Error in  Documentation Regarding Installation On Ubuntu 17

### ISSUE THREAD

**Issue by amanharitsh123** [sugarlabs/sugar#775]
Installation of Sugar desktop environment on ubuntu is version specific. The method provided in the documentation doesnt work in case of ubuntu 17 . There should be a link to the proper installation page in the documentation.

**Comment by quozl** [comment]
@amanharitsh123, which documentation are you referring to, and which version of Ubuntu?

I've checked, and README.md in this repository is correct, and https://sugarlabs.org/ points Ubuntu users to the Ubuntu page on our Wiki, and this is (a) has to be Ubuntu version specific because of bugs in Ubuntu, and (b) does work for me on both Ubuntu 17.04 and Ubuntu 17.10.

**Comment by amanharitsh123** [comment]
The provided command in the README.md  "sudo apt install sucrose" doesnt work in case of Ubuntu 17.10 (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=877812) . In the README.md we should provide links to the particular installation page for every flavour of Linux as it could save time for the newbies.

**Comment by quozl** [comment]
Yes, that's the bug, but it's not our bug.  The README.md predated Ubuntu 17.10 release, but does point to the Ubuntu page on our Wiki, which does mention the bug.  I don't think we need to document Ubuntu release-specific bugs in the Sugar source repository; that's the responsibility of Ubuntu or Debian.  We don't have the resources to document every flavour of Linux, let alone every release.  My preference is to remove the Ubuntu and Fedora guidance from README.md instead.

**Comment by amanharitsh123** [comment]
@quozl  Yes we should remove the ubuntu and fedora guidance and rather provide a common installation page link...

**Comment by quozl** [comment]
I don't think we have the resources to provide a common installation page link either.  Until now, we've pointed to last verified installation sequence for Fedora, Ubuntu or Debian.  And it's mostly been me.  Once this documenting causes misunderstanding or difficulty, and it can't be fixed at Sugar Labs, it's time to remove it.

**Comment by amanharitsh123** [comment]
Ubuntu :- http://wiki.sugarlabs.org/go/Ubuntu
Fedora :- http://wiki.sugarlabs.org/go/Fedora
Debian :- http://wiki.sugarlabs.org/go/Debian
Other Distro :- http://wiki.sugarlabs.org/go/Downloads#Do_you_use_GNU.2FLinux.3F
Cant we use these links in the main readme.md file ....Correct me if I am wrong :-)

**Comment by quozl** [comment]
Yes, that's mostly me.  So you propose moving maintenance of the instructions out of the source repository.  Why not instead move it the other way?

**Comment by amanharitsh123** [comment]
Sorry i am getting you. I am just trying to overcome a difficulty faced by me during the installation :-)

**Comment by quozl** [comment]
Let's wait for other opinions then.  Given that I've been maintaining both sets of instructions, without much help, I'm too close to the issue.

**Comment by amanharitsh123** [comment]
Ok sure :-)

**Comment by quozl** [comment]
As there have been no other opinions, and this issue was raised because of a bug in Debian that also affects Ubuntu, I'll close the issue.  Debian has since packaged 0.112, and Ubuntu has taken the new version, so it is unlikely to occur in the next Ubuntu release.
