### ISSUE TITLE
Journal Starts unexpectedly at the boot up in Ubuntu 17.10

### ISSUE THREAD

**Issue by amanharitsh123** [sugarlabs/sugar#776]
After testing Sugar Live Build , Sugar on ubuntu 16.04 , 17.04 and 17.10. I noticed that in case of ubuntu 17.10 Journal activity starts over Home activity at the boot unexpectedly. It seems like it automatically starts at the boot without any user response.

**Comment by quozl** [comment]
Thanks.  We know.  #769.  [#368](https://github.com/sugarlabs/sugar-toolkit-gtk3/issues/368).
