### ISSUE TITLE
Unable to Shutdown or Restart

### ISSUE THREAD

**Issue by timothybruggeman** [sugarlabs/sugar#782]
After typing a bit in the writing application, I went back to the main menu to restart the computer. A message popped up asking if I wanted to restart and discard my unsaved document. I clicked yes, but nothing happened. Then I clicked restart again, but allowing the timer to finish and still nothing happened. I tried clicking restart and shut-down several times, sometimes with the dialogue appearing, and sometimes without. No matter what, the computer would not shut down or restart. I ended up having to physically restart by holding the physical power button on the computer.

**Comment by quozl** [comment]
Works for me.  Not enough information.  What operating system distribution and version?  What does the Log activity show for the shell logs?

**Comment by aperezbios** [comment]
@timothybruggeman was this in a VM, on an XO, which version of Sugar, etc.

**Comment by timothybruggeman** [comment]
This was on SOAS. I'd like to think it was something to do with the unsaved document, but the problem still existed after I deleted everything in the Words application.

**Comment by quozl** [comment]
The Words activity or the Write activity?  It isn't clear now which you were using.

**Comment by quozl** [comment]
As it works fine for me, we'll need a method to reproduce, and also shell logs from an affected system.  Please re-open if these become available.
