### ISSUE TITLE
Home view still shows Browse if show_launcher = no

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar#785]
Reproducer: set Browse activity.info `show_launcher = no`, and restart Sugar.

Observed result: Browse is not shown in List View (F3, ctrl-2), but Browse is shown in Favorites View (F3, ctrl-1).

Expected result: Browse is not shown in either view.

`show_launcher` was proposed for deprecation in January 2014 on sugar-devel@.  We might finish deprecating it, or we might fix it so it works the way it should.

**Comment by Pro-Panda** [comment]
Fixed in  a21bff6 by hiding the activities with `show_launcher=no` from the favorite view as well.

Kindly let me know if it should it be deprecated instead ?

**Comment by quozl** [comment]
Reviewed.  Proceed.  Can activity be run by typing the name?  I'm hoping yes, but I don't know how it was meant to work.

**Comment by Pro-Panda** [comment]
If `show_launcher` is set to `no`, actvities aren't opening by typing the name as well. I suspect it is because the list of activities being searched is also generated via calling [this](https://github.com/sugarlabs/sugar/commit/8e0f1c65a05612e1de1c1db2db1c40ee1efb20ba#diff-0d0ca2d08502f03e6668d377ffd40520R310)

**Comment by quozl** [comment]
Thanks.

**Comment by Pro-Panda** [comment]
Out of curiousity, was the idea of `show_launcher` based on creating 'background processes' like activities, since there is no way to open an activity if its `show_launcher` is set to `no`

**Comment by quozl** [comment]
There is a way but it involves Terminal; using `bin/sugar-activity`.

`show_launcher` was first mentioned around July 2008 and was used by activities such as Read, before there was a journal object chooser.  Now, Read is not a favourite, and by using the object chooser is fine to run alone.

An introductory welcome activity was once started automatically on first use.

An introductory tutorial activity could use the feature.

`show_launcher` may also be used by developers or deployers for local bundles in `~/Activities`

**Comment by Pro-Panda** [comment]
Thank you for the explanation :smile:
