### ISSUE TITLE
activity icon not resized while in detail view in journal

### ISSUE THREAD

**Issue by Pro-Panda** [sugarlabs/sugar#799]
**Steps to reproduce:**
 - Open `CowBulls` activity
 - Close `CowBulls` activity
 - Open Journal
 - Open the detail view of the `CowBulls` activity
 - Activity icon of the image appears than the usual size

![journal-resize-bug](https://user-images.githubusercontent.com/28059150/41211149-24afce6c-6d53-11e8-90c9-5eacf6c50d30.jpg)

**Reproduced on:**
 - Ubuntu 16.04, Sugar 0.112
 - Ubuntu 18.04, Sugar 0.112

**Possible fix:**
 - Add a check to resize the icon to the desired size

**Comment by quozl** [comment]
No thanks.  Root cause is that the canvas size of CowBulls activity.svg is not (55px, 55px).  Please fix the icon.  See https://github.com/sugarlabs/sugar-docs/blob/master/src/sugar-iconify.md

**Comment by Pro-Panda** [comment]
Noted. Thanks
