### ISSUE TITLE
Fedora-SoaS-armhfp-29.1.2-sda.raw.zx image stuck at waiting a start job

### ISSUE THREAD

**Issue by jjliuhk** [sugarlabs/sugar#811]
I prepare a SD card (32G Samung EVO) with Fedora-SoaS-armhfp-29. 1.2-sda.raw.zx for my Raspberry Pi 3. It stuck at 

A start job is running for dev-disk...device ...

I waited for over 30 minutes for a couple times and I also tried to prepare the image by dd and Etcher.io but it still failed.

I wonder if someone can advise how to fix it.

**Comment by quozl** [comment]
No idea, sorry.  We don't have a start jobs for systemd in Sugar, so that message points to something in Fedora that hasn't worked, before Sugar is involved.  Do any of the other Fedora armhfp images work for you or do the same?

**Comment by nerdomancer** [comment]
Any update on this issue? I am running into it as well.

**Comment by quozl** [comment]
It isn't a problem we have any direct control over, because Sugar does
not use systemd.  I recommend you try a later version of Fedora, and
engage with the Fedora bug tracker.  If you don't want to bother with
that, install Raspbian, then install Sugar.
