### ISSUE TITLE
Neighbourhood view missing buddies with collaboration server in Fedora 29 and later

### ISSUE THREAD

**Issue by satellitee** [sugarlabs/sugar#814]
https://bugzilla.redhat.com/show_bug.cgi?id=1660597  even with prosody "telnet jabber.sugarlabs.org 5222" connected in terminal

**Comment by aperezbios** [comment]
I can independently confirm that, with jabber.sugarlabs.org configured as the presence server, under both Fedora 29 SoaS and SoaS  30/Rawhide, no other users are shown in the network neighborhood. Both versions of the Fedora SoaS are using Sugar 0.112.

**Comment by aperezbios** [comment]
Here are the contents of the shell.log on my SoaS 29:

```text

(main.py:2321): dbind-WARNING **: 14:54:56.449: Couldn't connect to accessibility bus: Failed to connect to socket 00010: Connection refused

(metacity:2495): dbind-WARNING **: 14:54:59.262: Couldn't connect to accessibility bus: Failed to connect to socket 00010: Connection refused

(metacity-message:2517): dbind-WARNING **: 14:55:07.250: Couldn't connect to accessibility bus: Failed to connect to socket 00010: Connection refused

(metacity-message:2518): dbind-WARNING **: 14:55:07.375: Couldn't connect to accessibility bus: Failed to connect to socket 00010: Connection refused
1545162984.979568 ERROR root: Error parsing public key.
1545162985.002976 ERROR dbus.connection: Unable to set arguments ('gabble', 'jabber', 'jabber', {'register': True, 'account': 'b7bb4f877acb2d6a4fa5883f3a3f35ed5abc730d@', 'require-encryption': True, 'resource': 'sugar', 'password': None, 'ignore-ssl-errors': True, 'old-ssl': True, 'port': dbus.UInt32(5223L), 'server': ''}, {'org.freedesktop.Telepathy.Account.ConnectAutomatically': True, 'org.freedesktop.Telepathy.Account.Enabled': True, 'org.freedesktop.Telepathy.Account.Nickname': 'Alex'}) according to signature u'sssa{sv}a{sv}': <type 'exceptions.TypeError'>: Don't know which D-Bus type to use to encode type "NoneType"
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 604, in msg_reply_handler
    reply_handler(*message.get_args_list(**get_args_opts))
  File "/usr/lib/python2.7/site-packages/jarabe/model/neighborhood.py", line 738, in __got_accounts_cb
    self._server_account = self._ensure_server_account(account_paths)
  File "/usr/lib/python2.7/site-packages/jarabe/model/neighborhood.py", line 851, in _ensure_server_account
    properties)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
TypeError: Don't know which D-Bus type to use to encode type "NoneType"
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/jarabe/model/neighborhood.py", line 864, in __jabber_server_changed_cb
    self._server_account.object_path)
AttributeError: 'NoneType' object has no attribute 'object_path'
```

**Comment by satellitee** [comment]
here are mine from soas f29: USB from sugar:

[satellit@localhost home]$ cd satellit
[satellit@localhost ~]$ ls
Desktop  Documents  Downloads  Music  Pictures  Public  Templates Videos
[satellit@localhost ~]$ cd .sugar
[satellit@localhost .sugar]$ ls
default
[satellit@localhost .sugar]$ cd default
[satellit@localhost default]$ ls
data  datastore  debug  favorite_activities  logs org.laptop.Terminal  
org.sugarlabs.IRC  owner.key owner.key.broken  owner.key.pub  
owner.key.pub.broken  terminalrc
[satellit@localhost default]$ cd logs
[satellit@localhost logs]$ ls
1545157353  1545157654  1545158680  1545161959  datastore.log 
org.laptop.Terminal-1.log  shell.log
[satellit@localhost logs]$ cd shell.log
bash: cd: shell.log: Not a directory
[satellit@localhost logs]$ shell log
bash: shell: command not found...
[satellit@localhost logs]$ pico shell log
bash: pico: command not found...
Similar command is: 'pic'
[satellit@localhost logs]$ pic shell.log
.lf 1 shell.log
1545161959.850952 ERROR root: Error parsing public key.
1545161977.826573 ERROR root: Error parsing public key.
1545161977.827080 WARNING root: Existing private key 
/home/satellit/.sugar/default/owner.key moved to 
/home/satellit/.sugar/default/owner.key.broken
1545161977.827310 WARNING root: Existing public key 
/home/satellit/.sugar/default/owner.key.pub moved to 
/home/satellit/.sugar/default/owner.key.pub.broken
1545161978.604816 ERROR root: Error parsing public key.
1545161978.607252 ERROR dbus.connection: Unable to set arguments 
('gabble', 'jabber', 'jabber', {'register': True, 'account': 
'35fbf8e1bf09bb84505e46482bc27ee3f72c0350@jabber.sugarlabs.org', 
'require-encryption': True, 'resource': 'sugar', 'password': None, 
'ignore-ssl-errors': True, 'old-ssl': True, 'port': dbus.UInt32(5223L), 
'server': 'jabber.sugarlabs.org'}, 
{'org.freedesktop.Telepathy.Account.ConnectAutomatically': True, 
'org.freedesktop.Telepathy.Account.Enabled': True, 
'org.freedesktop.Telepathy.Account.Nickname': 'Thomas Gilliard'}) 
according to signature u'sssa{sv}a{sv}': <type 'exceptions.TypeError'>: 
Don't know which D-Bus type to use to encode type "NoneType"
Traceback (most recent call last):
   File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 
604, in msg_reply_handler
     reply_handler(*message.get_args_list(**get_args_opts))
   File "/usr/lib/python2.7/site-packages/jarabe/model/neighborhood.py", 
line 738, in __got_accounts_cb
     self._server_account = self._ensure_server_account(account_paths)
   File "/usr/lib/python2.7/site-packages/jarabe/model/neighborhood.py", 
line 851, in _ensure_server_account
     properties)
   File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 70, 
in __call__
     return self._proxy_method(*args, **keywords)
   File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 145, 
in __call__
     **keywords)
   File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 
641, in call_blocking
     message.append(signature=signature, *args)
TypeError: Don't know which D-Bus type to use to encode type "NoneType"
/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py:1637: Warning: 
g_value_transform: assertion 'G_IS_VALUE (src_value)' failed
   return _Gtk_main(*args, **kwargs)
/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py:1637: Warning: 
unable to set property 'buddy' of type 'PyObject' from value of type 
'(null)'
   return _Gtk_main(*args, **kwargs)
1545162380.084754 WARNING root: no data for selection target MULTIPLE.
1545162380.096090 WARNING root: no data for selection target NULL.

**Comment by quozl** [comment]
Please list the Telepathy packages installed.  Thanks.

**Comment by aperezbios** [comment]
Additionally, the standard telepathy packages installed under F30/rawhide (as of the time this comment was written) are identical to the F29 packages.

**Comment by quozl** [comment]
Wild guess; the _error parsing public key_ results in a password of None which can't be encoded by D-Bus.  Almost as if a hash or crypto method was removed.  Corresponding log on Ubuntu 18.04 with Sugar 0.112 does not show the same sequence;

```
1544660315.103967 WARNING root: Journal premature deiconify by Metacity (RHBZ #1519042), try again.
/usr/lib/python2.7/dist-packages/jarabe/main.py:378: Warning: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed
  Gtk.main()
/usr/lib/python2.7/dist-packages/jarabe/main.py:378: Warning: unable to set property 'buddy' of type 'PyObject' from value of type '(null)'
  Gtk.main()
Gdk-Message: 12:43:27.520: metacity: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
```

**Comment by satellitee** [comment]
ssh -v Tgillard@sunjammer.sugarlabs.org 
works the keys in .ssh folder are correct ie:I can log in

**Comment by quozl** [comment]
> ssh -v ... works

Nothing to do with your SSH key ... or car keys.  :grin:  I was talking about the identity keys that Sugar creates on first login and presents to the server.  Next action is to debug the key creation sequence in Python.

**Comment by satellitee** [comment]
https://wiki.sugarlabs.org/go/File:Ssh_err_in_oracle.png
permission denied publickey  (Oracle Virtualbox)

**Comment by quozl** [comment]
@aperezbios, alternatively, check the `ssh-keygen` command used by Sugar;

https://github.com/sugarlabs/sugar/blob/master/src/jarabe/intro/window.py#L83

Can Fedora 29 generate DSA keys?  I'd hope so.

**Comment by aperezbios** [comment]
The result of my testing with Fedora SoaS versions 28, 29, and rawhide, which will become F30, is that the the import from sugar3.profile and invocation of get_pubkey() returns the expected key, so that path does not appear to be the source of the problem.

**Comment by aperezbios** [comment]
I also tested by manually invoking 'ssh-key -t dsa' on Fedora SoaS 28, 29, and rawhide, and the resulting DSA key is succesfully created.

**Comment by quozl** [comment]
Thanks!  Sounds like it will need interactive debugging.

**Comment by quozl** [comment]
```
>>> from sugar3.profile import get_profile
>>> p = get_profile()
>>> p.privkey_hash
ERROR:root:Error parsing public key
>>> p._hash_private_key()
ERROR:root:Error parsing public key
>>> ^D
% head -1 .sugar/default/owner.key
-----BEGIN OPENSSH PRIVATE KEY-----
```
OpenSSH has changed the format of the key file.

**Comment by FGrose** [comment]
Fixed commit 39b7e606 with f2289097

**Comment by satellitee** [comment]
Fedora-SoaS-Live-x86_64-Rawhide-20190102.n.0.iso
https://wiki.sugarlabs.org/go/File:20190102-fail.png  
liveinst and liveinst -T (text) fail

Fedora-KDE-Live-x86_64-Rawhide-20190102.n.0.iso installs in Oracle VB correctly?

**Comment by quozl** [comment]
@satellitee, thanks for your comment, but it is off-topic.  This GitHub issue is about missing buddies on Neighbourhood View.  I'll hide your comment and mine shortly.  But to answer your comment;

* you can add screenshots to GitHub without putting them on Wiki,
* the screenshot shows a different problem; liveinst -T spins the CPU and apparently does nothing useful, best to raise this with Fedora as liveinst is not a Sugar Labs component,
* i've no idea if the KDE variant installs correctly, sorry.  it's not really our business, is it?

**Comment by Kiy4h** [comment]
I'm experiencing this, on Debian 10.2 Sugar Live Build.

**Comment by quozl** [comment]
Might you be seeing https://github.com/sugarlabs/sugar/issues/840 instead?

**Comment by Kiy4h** [comment]
Oh, yes. My bad.

**Comment by Kiy4h** [comment]
Oh, yes. My bad.

**Comment by Kiy4h** [comment]
Oh, yes. My bad.
