### ISSUE TITLE
0.113 fails due to popwindow move incomplete

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar#822]
After login, the Sugar Home View does not appear, and control is returned to the display manager.  Log file `shell.log` contains;

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/jarabe/main.py", line 73, in <module>
    from jarabe.view import keyhandler
  File "/usr/lib/python2.7/dist-packages/jarabe/view/keyhandler.py", line 32, in <module>
    from jarabe.journal import journalactivity
  File "/usr/lib/python2.7/dist-packages/jarabe/journal/journalactivity.py", line 48, in <module>
    from jarabe.desktop.activitychooser import ActivityChooser
  File "/usr/lib/python2.7/dist-packages/jarabe/desktop/activitychooser.py", line 25, in <module>
    from sugar3.graphics.popwindow import PopWindow
ImportError: No module named popwindow
```

Fixed in a83257b.  Thanks to @pro-panda.

**Comment by aperezbios** [comment]
We need to incorporate this fix, and release 0.114, urgently.

**Comment by quozl** [comment]
Thanks.  Fix was already merged.

I'm waiting for feedback and testing of 0.113 before I release 0.114.

**Comment by Aniket21mathur** [comment]
@quozl Can we close this now?

**Comment by kushagra414** [comment]
@quozl I am still facing this issue.
I am using Ubuntu 19.10

**Comment by quozl** [comment]
Yes, that is caused by Debian and Ubuntu packaging latency, likely in turn because this bug hasn't been reported to Debian.  https://github.com/sugarlabs/sugar/blob/master/docs/ubuntu.md#ubuntu-1910-eoan-ermine has the detail.  Fix is to install Sugar 0.116.

**Comment by kushagra414** [comment]
@quozl How do I install Sugar-0.116?

**Comment by adarsh-qclw** [comment]
How do I install Sugar 0.116? I don't find it anywhere around.

**Comment by quozl** [comment]
Please use the sugar-devel@ mailing list for general questions.

https://github.com/sugarlabs/sugar/blob/master/docs/development-environment.md explains how to set up a development environment, and includes some developer-centric explanation for building and installing Sugar from source.  It is linked from this repository's README.md.  Or wait for your Linux distribution to package Sugar 0.116; which they probably won't do unless someone tells them.
