### ISSUE TITLE
Restore org.gnome.desktop.interface cursor-theme

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar#827]
The Sugar cursor affects the GNOME desktop environment.

This is caused by https://github.com/sugarlabs/sugar/blob/master/src/jarabe/main.py#L205 where the GNOME desktop cursor theme is changed to the Sugar theme.

Workaround is to use `gsettings` to change _cursor-theme_ in _org.gnome.desktop.interface_ back to what it was.  Or you can use `dconf` to reset all settings, but that has many side-effects.

* [ ] read the value of _cursor-theme_ before changing it in the `_start_window_manager` function,
* [ ] keep the _Gio.Settings_ instance instead of deleting at end of the `_start_window_manager` function,
* [ ] restore the old value in the `_stop_window_manager function`.

This should fix the problem for future users.

**Comment by kushagra98** [comment]
#828 Checked on my machine and works perfectly :smiley:
