### ISSUE TITLE
Running sucrose after installing new toolkit in Native method.

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/sugar#833]
Following the native method, after installing the new toolkit, to install sugar packages we are running `sudo apt install sucrose`. In this way aren't we overidding the new toolkit with the old one. Shouldn't we first do `sudo apt install sucrose` and then install the new toolkit to ensure that it is called on running sugar? @nswarup14 please give inputs.
@quozl what are your opinions?

**Comment by quozl** [comment]
Not in front of me at the moment, but don't the instructions say later to remove the packages?

-- 
James Cameron
http://quozl.netrek.org/

**Comment by Aniket21mathur** [comment]
Yes the instructions say that, but won't it be better If we install the toolkit latter. In that case the removal of packages would not be required. What do you think?

**Comment by quozl** [comment]
Well, the packages are being installed only to quickly satisfy the [dependencies wicked problem](http://lists.sugarlabs.org/archive/sugar-devel/2019-May/056876.html).  A simpler alternative is to get those dependencies using this method, then add them to the instructions, and perhaps also to a file DEPENDENCIES.debian in this repository.  Then in future the file will not change as Debian and Ubuntu package names change.  So I can see both sides of the problem.

**Comment by Aniket21mathur** [comment]
Thanks.
