### ISSUE TITLE
Error while inviting user to join a activity

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/sugar#841]
Got the following traceback while accepting invite from a user to join the Chat activity with head at
https://github.com/sugarlabs/sugar/commit/7aea5d1fbc9197dd325a05a6f66c1b42d7bb757b and https://github.com/sugarlabs/sugar/commit/325876f3ae671ad547b796affb5fbbec215523bd. 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 607, in msg_reply_handler
    *message.get_args_list()))
  File "/usr/local/lib/python2.7/dist-packages/jarabe/model/invites.py", line 73, in _handle_with_reply_cb
    raise error
dbus.exceptions.DBusException: org.freedesktop.DBus.GLib.UnmappedError.TpDbusErrorsQuark.Code2: Object /org/freedesktop/Telepathy/Client/org/laptop/Chat does not have interface org.freedesktop.Telepathy.Client.Handler

```
**Reproducer**
* Run Chat on two sugar instances
* From one instance share the chat activity to neighbourhood.
* From neigbourhood send invitation to the other instance.
* Accept invitation from the other instance.

**Ps**
Running toolkit at https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/412/commits/1233eec3d163f8ca86df675bebcba04272b93b5d

**Comment by Aniket21mathur** [comment]
@quozl closed the issue as the toolkit-code is not yet merged into master. But please have a look.

**Comment by pro-panda** [comment]
Reviewed.
Not reproduced. Will do when I get a chance

**Comment by Aniket21mathur** [comment]
Thanks :-)

**Comment by Aniket21mathur** [comment]
Testing https://github.com/sugarlabs/sugar/pull/837/commits/3dcd97a1d295b1f5602f87fa00b71500ebee3dd9 with toolkit v0.112 do not produce this error.

**Comment by quozl** [comment]
Your changes to src/sugar3/activity/activity.py removed DBusProperties
which has effect of not providing the three functions with
@dbus.service.method decorator; Get, Set, and GetAll.

Consequently, _ClientHandler isn't registered as a D-Bus interface.

**Comment by Aniket21mathur** [comment]
Thanks, adding those functions result in correct functioning.
