### ISSUE TITLE
Configure still checks for python-empy instead of python3-empy

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/sugar#858]

**Comment by quozl** [comment]
Also, on Fedora 30 there is no `/usr/bin/empy`, only `/usr/lib/python{2.7,3.7}/site-packages/em.py`, so the check fails.  "configure: error: python-empy is required".

**Comment by quozl** [comment]
I've a fix for this.

**Comment by quozl** [comment]
https://github.com/sugarlabs/sugar-artwork/commit/d47694d756bf04a5f8b407bcdef9af781798a8e7
