### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'add_window'

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar#864]
```log
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/jarabe/model/shell.py", line 624, in _window_opened_cb
    home_activity.add_window(window, is_main_window(window,
AttributeError: 'NoneType' object has no attribute 'add_window'
```

Reported by @bhulsken.

**Comment by iamprayush** [comment]
I'd like to work on solving this issue. I'm new here so could you please guide me on how to begin. Thanks in advance.

**Comment by quozl** [comment]
Thanks for offering.

To explain how to fix the issue I've looked at the traceback message, the source code near line 624, the entire function, the entire [log reported](https://github.com/sugarlabs/sugar/issues/787#issuecomment-522343301), and then considered the message in relation to the previous messages in the same log.

The traceback was a consequence of the Journal failing to start.  In turn the Journal failed because the Datastore failed.  The Datastore failed because the Journal sent a _limit_ as a floating-point value instead of an integer.  In turn this was use of `/` instead of `//` after porting to Python 3.

Since the traceback happened, we have [fixed the cause](https://github.com/sugarlabs/sugar/commit/0399b682089ee1fd6678163f3dac754f8e5308aa) and made a new release.

So the only remaining thing to do is to close this issue with an explanation.  Thanks for getting me to look at it! :grin:

**Comment by iamprayush** [comment]
Hi,
I actually used sugar labs and was thoroughly impressed with it. When I
found out that its open sourced, I wanted to contribute to it. Could you
help me pick a starting point to get familiar with the codebase or maybe
there are some issues I can help solve. I'm fairly proficient in python.
Thanks,
Prayush Dawda

**Comment by quozl** [comment]
For Python skills, best places to contribute to Sugar Labs are in the Sugar and activities software.

(For JavaScript skills, best places to contribute to Sugar Labs are in the Sugarizer and Music Blocks software.  See [programming languages](https://github.com/sugarlabs/sugar-docs/blob/master/src/languages.md) in case you have other skills.)

Your question about a starting point is common, but I've learned not to answer it; as my answers are usually ignored.  See my [general answer today](http://lists.sugarlabs.org/archive/sugar-devel/2019-September/057182.html) on the mailing list, especially "How to ask for directions?".

You asked about issues to solve.  It's not simple.  We have hundreds or thousands of problems, but not enough time for people to add them to GitHub issues, and even if we did we don't have enough people wanting to fix the problems.  We've seen that adding issues to GitHub doesn't get them fixed any faster.  Most problems are fixed with pull requests or commits rather than issues.  Fix problems by trying to use the software.  If you're not sure if a problem is real, ask others.

In future, please ask general questions like this on our mailing list.  Tacking your question on to the end of an unrelated issue excludes others from the discussion; and that's against our code of conduct.
