### ISSUE TITLE
Random text in output stream

### ISSUE THREAD

**Issue by worldinmyfist** [sugarlabs/sugar#871]
Issue : While changing the tty, random text appears on the output stream
Reproduction on the issue : Press Alt + Ctrl + F3 to change the tty. The screen comes as below : 
![index](https://user-images.githubusercontent.com/43772341/64199905-02022280-cea9-11e9-90c2-d339f61ad5e3.jpeg)

**Comment by aperezbios** [comment]
This appears to be a system-level problem, having absolutely nothing to do with Sugar.

**Comment by quozl** [comment]
I agree, nothing to do with Sugar.

**Comment by worldinmyfist** [comment]
Sir

I opened tty with Ubuntu it gave no issues , it is happening only with
sugar and I tried on two different laptops

**Comment by quozl** [comment]
Sugar doesn't provide tty except through the Terminal activity.  You're using a feature of your operating system that Sugar has nothing to do with.
