### ISSUE TITLE
Cursor changed automatically

### ISSUE THREAD

**Issue by worldinmyfist** [sugarlabs/sugar#872]
Issue: When I installed sugar desktop environment, the cursor automatically changed on ubuntu even though I did not do it explicitly
The cursor is same as that of sugar DE.

![WhatsApp Image 2019-09-04 at 9 10 28 AM](https://user-images.githubusercontent.com/43772341/64224150-17e90500-cef4-11e9-9fab-4495df18db35.jpeg)

**Comment by quozl** [comment]
Yes, known problem.  See https://github.com/sugarlabs/sugar/issues/827

**Comment by deejoe** [comment]
Could this be closed as a duplicate, then?

**Comment by worldinmyfist** [comment]
Yes
