### ISSUE TITLE
Add a list of dependencies

### ISSUE THREAD

**Issue by srevinsaju** [sugarlabs/sugar#884]
```
$ ss@ss-srevinsaju:~/repo/sugar$ ./autogen.sh
./autogen.sh: 11: intltoolize: not found
configure.ac:28: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
configure.ac:28: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

```

An error encountered while making sugar DE. Please add information to `README` on what `intltoolize` is.

w.r.t Google Code-In

**Comment by quozl** [comment]
Thanks for the feedback.

The _intltoolize_ command is used by `autogen.sh` and provided by the _inttool_ package.  The need for _intltool_ package is satisfied by `apt build-dep sugar` on Ubuntu 19.10, and this is mentioned by our [Setup a development environment - Native Sugar](https://github.com/sugarlabs/sugar/blob/master/docs/development-environment.md), which relies on the Debian developers' idea of what we depend on.

We once did, but now we **don't maintain** a set of dependencies for Sugar.  We could do so if there is an interest in maintaining the list.  So far I've not seen interest.  I'll change the title of this issue to look for that interest.  For the list to be acceptable it must;

* [ ] be complete, and;
* [ ] be not specific to any particular distribution of Linux; or mention at least Fedora and Debian package names.

**Comment by srevinsaju** [comment]
@quozl , thanks. I am new to build-dep, but the first README. md makes building from SOURCE simple. I suggest you to add, this line :
"Refer Setup a development environment" thing.
because at first I didn't want to develop, but only run it somehow. I will check the build-dep method

**Comment by quozl** [comment]
@srevinsaju, there's already a line that does that.  If you only want to run Sugar, then installing Sugar is more easily done using `apt install sucrose` than building from source.

**Comment by srevinsaju** [comment]
@quozl it is not working on Ubuntu 19.10 . what is a presumed solution? 

_Sent from my Galaxy Note2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by quozl** [comment]
Please don't post the same problem into multiple threads.

**Comment by srevinsaju** [comment]
I guess keeping a list of dependencies and this thread is redundant, it was specific to a particular version. Now fixed. Closing :smile:
