### ISSUE TITLE
[QUESTION] How to install sugar3 python package?

### ISSUE THREAD

**Issue by srevinsaju** [sugarlabs/sugar#889]

**Comment by quozl** [comment]
Thanks for asking.

* [README.md](https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/master/README.md) particularly the "configure, make, make install",
* [Setup a Development Environment - Native Sugar](https://github.com/sugarlabs/sugar/blob/master/docs/development-environment.md#native-sugar) particularly the sections that refer to _sugar-toolkit-gtk3_.
