### ISSUE TITLE
Error while building sugar in make install command

### ISSUE THREAD

**Issue by garvitgupta08** [sugarlabs/sugar#894]
This is the error

$ make install
Making install in bin
make[1]: Entering directory '/home/ggupta08/sugar/bin'
make[2]: Entering directory '/home/ggupta08/sugar/bin'
 /bin/mkdir -p '/usr/local/bin'
 /usr/bin/install -c sugar sugar-serial-number-helper sugar-backlight-helper sugar-backlight-setup sugar-control-panel sugar-install-bundle sugar-erase-bundle sugar-launch '/usr/local/bin'
/usr/bin/install: cannot create regular file '/usr/local/bin/sugar': Permission denied
/usr/bin/install: cannot create regular file '/usr/local/bin/sugar-serial-number-helper': Permission denied
/usr/bin/install: cannot create regular file '/usr/local/bin/sugar-backlight-helper': Permission denied
/usr/bin/install: cannot create regular file '/usr/local/bin/sugar-backlight-setup': Permission denied
/usr/bin/install: cannot create regular file '/usr/local/bin/sugar-control-panel': Permission denied
/usr/bin/install: cannot create regular file '/usr/local/bin/sugar-install-bundle': Permission denied
/usr/bin/install: cannot create regular file '/usr/local/bin/sugar-erase-bundle': Permission denied
/usr/bin/install: cannot create regular file '/usr/local/bin/sugar-launch': Permission denied
Makefile:337: recipe for target 'install-binSCRIPTS' failed
make[2]: *** [install-binSCRIPTS] Error 1
make[2]: Leaving directory '/home/ggupta08/sugar/bin'
Makefile:421: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/ggupta08/sugar/bin'
Makefile:398: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by garvitgupta08** [comment]
sudo make install worked.

**Comment by quozl** [comment]
Good, `sudo make insatll` is in our documentation;
https://github.com/sugarlabs/sugar/blob/master/docs/development-environment.md
