### ISSUE TITLE
Sugar Not Available For ChromeOS. 

### ISSUE THREAD

**Issue by RishiR21** [sugarlabs/sugar#895]
Hello there, I am Rishi R from Google Code-in. An issue I found with Sugar is that ChromeOS users don't access to Sugar on a Stick while using the ChromeOS. This looks to be a problem considering the fact that a majority of the students using the Sugar on a Stick Platform are students who could be using Chromebooks.

**Comment by quozl** [comment]
Thanks.  ChromeOS users can install Sugarizer.
