### ISSUE TITLE
User data not saved on forced shutdown

### ISSUE THREAD

**Issue by srevinsaju** [sugarlabs/sugar#903]
User data of a new user is not saved by sugar on a forced shutdown (possibly, power button) and it can have potential data loss in other components too

STEPS TO REPRODUCE:
* Start a sugar debian Live Build 0.116
* Install it to HDD
* Restart and enter login information
* Enter user data
* Force close VM without ACPI shutdown
* Restart VM, login with same user information

You will notice sugar asks for Name, Grade again

**Comment by quozl** [comment]
Yes, and this is unavoidable without slowing down Sugar by adding a wait for data to be written to media.  On OLPC OS on the XO laptop, the jffs2 filesystem and powerd daemon took care of this for us; touching the power button caused a filesystem synchronisation before power was lost.  On conventional operating systems such as Debian, data loss will _always_ occur if the virtual machine is terminated before the Linux kernel completes a write-back of dirty filesystem pages.  This will happen with Debian independently of Sugar, so my argument is that this is a Linux problem, not a Sugar problem.  My preference is not to fix it, instead concentrating on performance over data safety.  Power loss or forced closed is not a normal scenario to control for.

**Comment by rabbitholecomputing** [comment]
Agreed, this is definitively _not_ a Sugar-specific problem. The same thing can and does happen under Windows, and MacOS.

**Comment by srevinsaju** [comment]
Makes sense. Closing this :smile:
