### ISSUE TITLE
Add Continuous Integration, Build Tests

### ISSUE THREAD

**Issue by srevinsaju** [sugarlabs/sugar#907]
As `sugar`, `sugar-toolkit-gtk3`, `sugar-artwork` and `sugar-datastore` are quite important repositories, It would be necessary to test new PRs, and other commits, for example to see if it fits the flake8 formatting guidelines, an untested SyntaxErrors. This might automate the workload of the reviewer

**Comment by quozl** [comment]
We do test new pull requests and other commits.  See [Guide for Reviewers](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#guide-for-reviewers).  If you think this is too hard, then you can leave it for me.

I've assessed continuous integration possibilities often.  We have no test suite.  We have no test infrastructure.  Fixing those two would cost more effort than any of us are willing to put into the project.  (I would use either xdotool or an AxiDraw with a stylus).

It is also no substitute for careful human testing.  Continuous integration always creates a bias toward accepting anything that passes the tests, as reviewers begin to rely on automation.  You can read research on this in the field of human factors, and airplane cockpit systems design.  We also see it in everybody who uses `2to3` or other tools.

So, costs a lot, gives us little, takes away some.
