### ISSUE TITLE
"Registration Failed Cannot connect to the server"

### ISSUE THREAD

**Issue by ericspivey** [sugarlabs/sugar#912]
Running sugar on Ubuntu 18.04, cannot register, with following failure message:
"Registration Failed Cannot connect to the server" no other instructions

**Comment by quozl** [comment]
Thanks.  This will work if you have an School Server on your local network, otherwise it won't.  There is no need to register the software, as Sugar is released under the GPLv3 open source license.

**Comment by ericspivey** [comment]
Ah, sorry, I didn't realize that was only a feature for school servers. As I am only working with one child at home, I think we will just use the sugarize web interface, then.
