### ISSUE TITLE
calcalculator outputs error checking funtion if graph function is changed to "f(y) ="

### ISSUE THREAD

**Issue by phoenix14113** [sugarlabs/sugar#916]
function f(y) {      if (arguments.length != 1) {        throw new SyntaxError("Wrong number of arguments in function f (" + arguments.length + " provided, 1 expected)");      }      return y    }

This is output if you change the graphing function f(x) to another variable f(y). Numbers and symbols output the correct, right column, formatted error handling but letters, with the exception of x, output the actual code.

**Comment by quozl** [comment]
@llaske, this would appear to be Sugarizer, not Sugar.

**Comment by phoenix14113** [comment]
> @llaske, this would appear to be Sugarizer, not Sugar.

oops.. sorry
