### ISSUE TITLE
Fedora 33 SOAS Live Environment cannot login

### ISSUE THREAD

**Issue by chrisafraser** [sugarlabs/sugar#933]
Using Fedora-SoaS-Live-x86_64-33-1.2.iso downloaded from https://spins.fedoraproject.org/en/soas/ as of 2020-10-28 prompts for username/password, preventing login/startup.

<img width="800" alt="Screen Shot 2020-10-28 at 10 11 35 AM" src="https://user-images.githubusercontent.com/36118973/97449144-c1186900-1907-11eb-8e68-0b97b79b9d0e.png">

Switching back to the fedora 32 variant works as expected.

**Comment by chimosky** [comment]
Yeah there's an ongoing discussion about it [here](https://lists.fedoraproject.org/archives/list/test@lists.fedoraproject.org/thread/RBGA5YLXU52LAFTVAIWWGXWQQQ2GEYZA/).

**Comment by quozl** [comment]
Not something we can fix in Sugar.  We don't own the display manager.
