### ISSUE TITLE
Activities failed to start

### ISSUE THREAD

**Issue by aditya113141** [sugarlabs/sugar#937]
I installed Sugar environment on Raspberry Pi. I downloaded some activities from https://activities.sugarlabs.org/ but they are not starting.  
https://drive.google.com/file/d/1gbJkNFZWzleMr7HxG4qrbsM9GLwKKn5c/view?usp=sharing

**Comment by srevinsaju** [comment]
Which version of Sugar are you running? What Linux are your running? Is it Raspbian?

**Comment by aditya113141** [comment]
I am using Raspbian OS. The version of sugar  is -> 0.117.olpc.0

**Comment by srevinsaju** [comment]
Right. The bundle you have downloaded from https://activities.sugarlabs.org is legacy. For bundles supporting v0.117 of Sugar (python3), you would like to get the bundles from https://v4.activities.sugarlabs.org

**Comment by quozl** [comment]
@aditya113141, yes, that's expected, and you can help fix it.  Flappy's next step is to release it on v4.activities.sugarlabs.org.

@srevinsaju Agreed.

For development purposes, alternatives to using bundles are;

* distributed tar files in https://download.sugarlabs.org/sources/honey/ with recent dates after the Python 3 port release,
* distributed tar files in https://download.sugarlabs.org/sources/sucrose/fructose/ (though if you are using Raspbian with my 0.117.olpc.0 packages [from here](https://people.sugarlabs.org/quozl/rb/) many of these activities may have been installed already),
* `cd ~`, `git clone`, and `./setup.py dev`

**Comment by aditya113141** [comment]
I want to work on upgrading the Flappy game. Can you please share some more information on it ?

**Comment by quozl** [comment]
Sure.  We have;

* a [guide to modifying activities](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#modifying-activities),
* a [repository called _flappy_](https://github.com/sugarlabs/flappy),
* a [repository called _flappy-birds-activity_](https://github.com/sugarlabs/flappy-birds-activity).

Elsewhere, you can find resources on programming in Python, with PyGObject, with GTK, and so on.

You goal should be to make it work, and make a release.  It might already work, and might only need a release.

If you have any more specific questions, please ask.  It is not worth us speculating about what to tell you, because that could take longer than doing the work ourselves.  We expect you to try to solve most things yourself.

Remember I'm not giving you permission.  We are a permissionless community.

**Comment by aditya113141** [comment]
Sure, Sir. I am on it.

**Comment by aditya113141** [comment]
I am not able to upload bundle on v4.activities.sugarlabs.org 

The error I get -

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting aslo4
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/aslo4/

**Comment by srevinsaju** [comment]
It is not possible to upload the activity to `aslo-v4` directly. You will first have to demonstrate your skills at maintaining activities. See  [contributing.md](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#modifying-activities) for more information regarding becoming a maintainer and tasks which you need to fulfil before becoming a maintainer..

**Comment by quozl** [comment]
Thanks @aditya113141.  You do not need to copy or run  https://github.com/sugarlabs/aslo-v4 at all, as it is a service we provide at Sugar Labs.  You only need to provide data for the service.  However, as @srevinsaju points out, you can only do that if you have an account on our shell server sunjammer.  We give accounts to people who are members or have demonstrated contribution.  I look forward to that!

**Comment by aditya113141** [comment]
I am not able to understand one thing. I cloned the Flappy repo and installed it using `python3 setup.py dev` . The activity was running fine on the PC . But the .xo file I downloaded from activities.sugarlabs.org is not working.

**Comment by aperezbios** [comment]
@aditya113141 that's because the version of Flappy in the repo is current, and the version on ASLO is from 2018:

http://activities.sugarlabs.org/en-US/sugar/addon/4731

**Comment by aditya113141** [comment]
Ok, so there is no need of making any changes for releasing it on  https://v4.activities.sugarlabs.org. It works perfectly and only requires a release.

**Comment by quozl** [comment]
Thanks for the test report.  I was unaware it was working perfectly.  v5 released.  https://v4.activities.sugarlabs.org/app/org.ceibaljam.flappy.html
