### ISSUE TITLE
PermissionError when trying to install an activity.

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/sugar#946]
Noticed this while trying to update viewslides activity in F35 SOAS - comes with Python 3.10 -.

Running `./setup.py install --prefix=/usr` throws a `PermissionError` with traceback;
```python3
Install /usr/share/sugar/activities/MathHurdler.activity/.bashrc
Traceback (most recent call last):
  File "./setup.py", line 3, in <module>
    bundlebuilder.start()
  File "/usr/lib/python3.7/dist-packages/sugar3/activity/bundlebuilder.py", line 653, in start
    globals()['cmd_' + (options.command or '')](config, options)
  File "/usr/lib/python3.7/dist-packages/sugar3/activity/bundlebuilder.py", line 527, in cmd_install
    options.install_desktop_file)
  File "/usr/lib/python3.7/dist-packages/sugar3/activity/bundlebuilder.py", line 319, in install
    os.makedirs(path)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/share/sugar/activities/MathHurdler.activity'
```

There's a proposed fix for this in [Python](https://github.com/python/cpython/pull/23901) but if merged, it'll be included in Python 3.10.

@aperezbios this might stall the update of viewslides downstream, I haven't noticed this with any other package at the moment.

Opening this so I'll not forget to take a look at this later.

**Comment by quozl** [comment]
Until Python is fixed, your choices include;

* use the shell to make the directories, or
* ask for the Python fix to be backported into the Python package you are depending on.

**Comment by chimosky** [comment]
I think using the shell to make the directories seems viable in the short term and might be the best thing to do at the moment.

**Comment by chimosky** [comment]
Temporary fix exits at sugarlabs/sugar-toolkit-gtk3@9605f81.

**Comment by chimosky** [comment]
After investigating I'd figured out what was causing the problem in fedora so I've reverted sugarlabs/sugar-toolkit-gtk3@9605f81.
Closing this.

**Comment by quozl** [comment]
Oh wow, yes, I see why now.  I guess I should have looked at the Fedora repository before, given this was a problem with Fedora only.

**Comment by chimosky** [comment]
> Oh wow, yes, I see why now. I guess I should have looked at the Fedora repository before, given this was a problem with Fedora only.

And it was a bit subtle, some files that let you run sugar applications outside sugar weren't deleted and they usually are as they break the build and they were being referenced in the buildroot path so I'd changed the path to just the prefix `/usr` and that was what caused the permission error.

**Comment by quozl** [comment]
Well done.

**Comment by chimosky** [comment]
> Well done.

Thanks.
