### ISSUE TITLE
apps broken after software update

### ISSUE THREAD

**Issue by falconict** [sugarlabs/sugar#947]
I have two machines with Debian 10 using SDDM and LXQT and a 686-pae kernel, to both of which I have added the Sugar 0.112 environment.  The environment and activities were working fine for weeks.  Today I decided to update one of the machines using the Sugar 'software update' facility, and this has rendered all Sugar applications unusable, all returning 'failed to start'.

What is curious is that the package versions as reported by 'dpkg -l | grep sugar' on both machines is identical:
ii  gir1.2-sugarext-1.0                   0.112-3                                 i386         Sugar Learning Platform - toolkit GObject introspection
ii  libsugarext-data                      0.112-3                                 all          Sugar Learning Platform - toolkit common files
ii  libsugarext0:i386                     0.112-3                                 i386         Sugar Learning Platform - toolkit runtime library
ii  python-sugar3                         0.112-3                                 all          Sugar Learning Platform - toolkit Python bindings
ii  sugar-browse-activity                 202-2                                   all          Sugar Learning Platform - web browsing activity
ii  sugar-calculate-activity              44-3                                    all          Sugar Learning Platform - calculation activity
ii  sugar-chat-activity                   84-2                                    all          Sugar Learning Platform - text chatting activity
ii  sugar-icon-theme                      0.112-1                                 all          Sugar Learning Platform - icon theme
ii  sugar-imageviewer-activity            63-1                                    all          Sugar Learning Platform - image viewing activity
ii  sugar-jukebox-activity                33-1                                    all          Sugar Learning Platform - music jukebox activity
ii  sugar-log-activity                    38-1                                    all          Sugar Learning Platform - log viewing and reporting activity
ii  sugar-pippy-activity                  71~dfsg-1                               all          Sugar Learning Platform - Python programming activity
ii  sugar-read-activity                   120-2                                   all          Sugar Learning Platform - document viewer activity
ii  sugar-session                         0.112-6                                 all          Sugar Learning Platform - window manager
ii  sugar-terminal-activity               45.2-1                                  all          Sugar Learning Platform - terminal emulation activity
ii  sugar-themes                          0.112-1                                 all          Sugar Learning Platform - artwork
ii  sugar-write-activity                  99-2                                    all          Sugar Learning Platform - writing activity

Even more curious is on the broken machine, the app version returned by the Sugar interface does not match the one shown above.  For example, Sugar on the broken machine says that the Write version is 100, whereas dpkg shows 99-2.

I have tried to remove and reinstall the environment, to no avail, using
apt-get remove *sugar*
apt-get purge *sugar*
apt-get clean
apt-get autoclean
apt-get install sugar

The outcome is still the packages reported by Sugar on the broken machine not matching the packages reported by dpkg even after redownloading the older ones, and failing to start.

Why does the software update facility fail in this way?  Also, what can I do to restore a working Sugar environment, short of wiping the machine clean completely?

From within the LXQT environment, the Write and other apps launch as normal when invoke through the Education grouping, so the issue seems to be located within Sugar.

**Comment by quozl** [comment]
That's the expected outcome.  Sugar's software update will have applied the changes to the user account only, so you can reverse that by moving the ~/Activities directory to a different name and restarting Sugar.  Long term, think about upgrading Debian and Sugar to later versions, then try the software update again.  Doing this in a VM would be safest.

**Comment by falconict** [comment]
Thank you, that's resolved the matter.  Yes will upgrade soon.
