### ISSUE TITLE
Fedora 35 SoaS image can't log in due to missing python3-decorator dependency

### ISSUE THREAD

**Issue by aperezbios** [sugarlabs/sugar#950]
As part of issue #938, it was discovered that there's a missing python3-decorator dependency in the Fedora 35 SoaS image. I felt this deserved its own bug for tracking purposes. Here's the link to the fix on the Fedora/packaging side: https://src.fedoraproject.org/rpms/sugar-toolkit-gtk3/c/cc57924206c0bab0b1e9f2cfb3b4c244371ce18e?branch=rawhide

The Fedora-packaged version of the 'decorator' python3 package is named python3-decorator, and can be installed by pressing ctrl-alt-F2, logging in as 'liveuser' (there's no password), and then running 'dnf install -y python3-decorator'

**Comment by aperezbios** [comment]
Closing, as this is not an actual bug against Sugar itself, but an issue with Fedora packaging. See above link with the fix, which will eventually get in to Rawhide.

**Comment by quozl** [comment]
I'm new to how Fedora works these days, but can someone explain to me why this problem hasn't been fixed in Fedora 35 yet?

**Comment by chimosky** [comment]
It has been fixed for F36, I had an issue with building for F35 and couldn't look into it at the time, will look into it once I can.

Basically I just need to run a build for F35 in bodhi.

**Comment by quozl** [comment]
Thanks.  So it depends on individual developers and isn't a function of the Fedora project as a whole?  That would explain why it keeps happening.  Is there any CI that can be added to prevent publishing the SoaS spin if it doesn't start Sugar?  e.g. something that does a boot test, checks if Sugar started, and returns a status code.

**Comment by aperezbios** [comment]
Correct. We may be able to set up some CI ourselves, and if that's possible, we should do so.

In the meantime, anyone who wants a working SoaS LiveUSB/LiveCD environment can use this Fedora Rawhide nightly which I've tested, and verified boots to the desktop. [http://download.sugarlabs.org/Fedora-SoaS-Live-x86_64-Rawhide-20220124.n.0.iso](http://download.sugarlabs.org/Fedora-SoaS-Live-x86_64-Rawhide-20220124.n.0.iso)

**Comment by chimosky** [comment]
> Thanks. So it depends on individual developers and isn't a function of the Fedora project as a whole? That would explain why it keeps happening. Is there any CI that can be added to prevent publishing the SoaS spin if it doesn't start Sugar? e.g. something that does a boot test, checks if Sugar started, and returns a status code.

I think it's possible to setup a CI for that, something to work on once I can.
