### ISSUE TITLE
Unable to download Sugar on Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by nikkuAg** [sugarlabs/sugar#955]
I was trying to set up sugar for development purposes to solve some issues and after running the command `sudo apt install sucrose`,
I got an error saying `E: Unable to locate package sucrose`

**Comment by quozl** [comment]
Yes, well-known problem, the sucrose package was not in Debian at the time that Ubuntu 20.04 froze their non-core package set.  Use another version of Ubuntu.

**Comment by quozl** [comment]
https://github.com/sugarlabs/sugar/issues/943 had a complete discussion, please read the issue comments for ideas.
