### ISSUE TITLE
Installing Sugar on WSL

### ISSUE THREAD

**Issue by nikkuAg** [sugarlabs/sugar#956]
Is it possible to install sugar on wsl with Ubuntu 18.04.

If possible what step to follow after installation.

**Comment by chimosky** [comment]
It might be possible but I haven't tried, maybe something you might want to try and write about?

**Comment by quozl** [comment]
Once you have Ubuntu 18.04 running, yes, installing Sugar is possible.  It doesn't make much[^1] difference if you have Ubuntu 18.04 running on native CPU, hypervisor, or Windows Subsystem for Linux 2.

[^1]: Some Sugar features, such as wireless connections, battery management, mouse position tracking or gesture recognition, are only available on a native CPU, but that's only important if you are developing those features.

You can read our [installing on Ubuntu 18.04 steps](https://github.com/sugarlabs/sugar/blob/master/docs/ubuntu.md#ubuntu-1804-bionic-beaver-and-1810-cosmic-cuttlefish).  But that only gets you Sugar 0.112.  Enough if your purpose is to try out Sugar, but not enough if you wish to develop for Sugar Labs.

Our article [Setup a development environment](https://github.com/sugarlabs/sugar/blob/master/docs/development-environment.md) describes three methods that may be of interest.
