### ISSUE TITLE
WebKitErrorDomain: WebKit encountered an internal error (300)

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar#962]
On Ubuntu 22.04, Browse cannot load any web page except for the local start page.

![Screenshot_ujj_2022-04-18_14:46:44](https://user-images.githubusercontent.com/2936481/163755967-166b2a07-ba51-407a-8393-fc66fa6e083f.png)

Activity logs contain

```log
**
GLib-GIO:ERROR:../../../gio/gsocketclient.c:1982:g_socket_client_enumerator_callback: assertion failed: (data->error_info->best_error)
Bail out! GLib-GIO:ERROR:../../../gio/gsocketclient.c:1982:g_socket_client_enumerator_callback: assertion failed: (data->error_info->best_error)
```

**Comment by quozl** [comment]
Thanks for your help.  It was the https_proxy environment variable set to an empty string.  I've fixed it in Sugar.  As the fix is tested, simple, and not likely to be contentious, I skipped a pull request.  The fix can be applied to already installed Sugar package, and then restart Sugar for it to take effect.

**Comment by chimosky** [comment]
> Thanks for your help. It was the https_proxy environment variable set to an empty string. I've fixed it in Sugar. As the fix is tested, simple, and not likely to be contentious, I skipped a pull request. The fix can be applied to already installed Sugar package, and then restart Sugar for it to take effect.

Thanks!

**Comment by acronie** [comment]
Hello. I'm facing the same problem with the browser being unable to load web pages from https under the last Ubuntu version. Could you explain here what we should do to fix an already installed Sugar package ?
I gave `apt-get update` a try, but no luck.
Sorry for the newbie question... and thanks for your advices.

**Comment by quozl** [comment]
Hello @acronie,

For a quick fix, become the root user, edit the file `/usr/lib/python3/dist-packages/jarabe/main.py`, find the text `def setup_theme`, and remove the three lines of code above it;

Before:

```log
    elif g_mode == 'none':
        for each_env_variable in env_variables:
            os.environ[each_env_variable] = ''


def setup_theme():
```

After:

```log


def setup_theme():
```

Then restart Sugar.  This will fix it for one system, but the fix may be lost if the system is updated by Ubuntu.  You can block that with the command `sudo apt-mark hold python3-jarabe`.

For a fix that changes Ubuntu,  report a bug to Ubuntu and refer to this issue as what worked for you.  Ubuntu can then apply the [patch](https://github.com/sugarlabs/sugar/commit/a0f0ec19dbb55906e2be01f7f7d976f4e9c251f5) to their package.  They may not have time to do so, because Sugar is not a priority.

Ubuntu get this package from Debian.  When Debian fix it, Ubuntu will likely have it in the next release, so you can also report the bug to Debian.

Otherwise, when we release the new version, Debian and Ubuntu will eventually have the fix, sometimes years later.  I think the record is about four years.

**Comment by acronie** [comment]
Thanks @quozl! I could manage to fix it with your indications.
I'm experimenting various configurations in order to install Sugar on multiple old desktop that "landed" in the school of my daughters.
I tried with Fedora today, and it's globally easier and more complete to install Sugar on it than on Ubuntu (and variants).

**Comment by quozl** [comment]
Thanks.  So is Fedora also affected by this problem?

**Comment by acronie** [comment]
Not at all! I just installed a fresh Fedora workstation 37 on the PC, then installed Sugar through the tutorial's given terminal command, switch the desktop environnement by login out-selecting Sugar-login in, and everything was working, Browser including. So, there's nothing to fix on Fedora about this WebKit error.

**Comment by quozl** [comment]
That's great.  Well done to the Fedora package maintainers for Sugar.
