### ISSUE TITLE
Feat: Setup GH Issue and PR templates

### ISSUE THREAD

**Issue by samyakshah3008** [sugarlabs/sugar#973]
## Description: 

- Currently any new user who comes up to this repository and reports a new issue ticket, we don't have a template. For a better contributor experience, also there is no template for PR while raising one. 

## Potential Solution: 

- We can create a markdown file for the same.

## Helpful links: 

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository

**Comment by samyakshah3008** [comment]
Similar PR for reference: 
https://github.com/sugarlabs/musicblocks/pull/3469

**Comment by HitanshuPrasad** [comment]
Working on this issue

**Comment by samyakshah3008** [comment]
> Working on this issue

Cool

**Comment by quozl** [comment]
Thanks, but we already have a severe lack of issues, I don't wish to do anything to hinder the reporting of issues.  I won't be using a template, and recommend against using a template.  We need to be welcoming of issue reporters instead of creating barriers.

**Comment by samyakshah3008** [comment]
Oh, fair enough @quozl I got your point.
