### ISSUE TITLE
Port to WebKit2 4.1

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar#974]
Per Debian bug 1061531, the 4.0 API is replaced by 4.1, and uses libsoup3.

**Comment by jbicha** [comment]
Fedora has [stopped](https://fedoraproject.org/wiki/Changes/Remove_webkit2gtk-4.0_API_Version) building the 4.0 API in preparation for the release of Fedora 40 in a few months. Debian and Ubuntu are working to remove the 4.0 support too.
