### ISSUE TITLE
[DOCS] Add documentation for installing on Macos 

### ISSUE THREAD

**Issue by mohitvdx** [sugarlabs/sugar#976]
Currently, the documentation only have instructions to run this on ubuntu or debian or fedora systems. 

Add documentation to install it on MacOS

**Comment by chimosky** [comment]
We currently don't have a means of running sugar directly on MacOS, you can run sugar in a vm on MacOS and it should work fine.

I'll close this issue as it's not a priority at the moment and the existing documentation does offer a means to run Sugar on MacOS, not just directly as I'm guessing that's what you're referring to.

**Comment by quozl** [comment]
You can get Sugarizer app for macOS, a JavaScript reimplementation of Sugar that does not act as a desktop environment replacement.  https://sugarizer.org/

**Comment by mohitvdx** [comment]
<img width="264" alt="Screenshot 2024-02-10 at 3 12 29 PM" src="https://github.com/sugarlabs/sugar/assets/112820522/e4395398-25ab-4821-8f53-210b2cc33d64">

Running Sugarizer App for macOS gives this error.

Is there some way to run the sugar development environment in macos? 
I desired to contribute to sugar activities @quozl

**Comment by quozl** [comment]
https://github.com/llaske/sugarizer is where Sugarizer is developed.  That doesn't look like an error, but a normal code signing prompt.

Yes, you could run a virtual machine and inside that run Debian, Ubuntu, Fedora, or some other Linux.  You can then configure XCode or VSCode to reach into the virtual machine.
